<script setup></script>

<template>
    <ul class="overflow-y-scroll h-[calc(100%_-_120px)] divide-y divide-slate-600 mt-6">
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><input class="p-2 me-2 w-full bg-slate-600 outline-0 border-none flex items-center rounded-md" type="text" value="Label o Titulo de la tarea" /><div class="hidden flex-shrink-0 md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        <li class="flex justify-between items-center"><label class="p-2 w-full truncate flex items-center md:max-w-xl"><input class="me-1 cursor-pointer" type="checkbox"/>Label o Titulo de la tarea</label> <div class="hidden md:inline-block"><button class="bg-red-500 mx-1 w-8 h-8 hover:bg-red-400 transition-colors rounded-md">X</button><button class="bg-green-500 mx-1 w-8 h-8 hover:bg-green-400 transition-colors rounded-md">Z</button></div></li>
        
    </ul>
</template>